version: '3.1'

services:
  server:
    container_name: server
    build: ./server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    restart: always
    ports: 
      - 8080:80

  client:
    container_name: client
    build: ./client
    command: uvicorn app.main:app --host 0.0.0.0 --port 100
    restart: always
    depends_on:
      - server
    ports:
      - 8081:100

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client